version: '3'

services:
   ui-service:
      image: ghcr.io/felixsteinke/organzier-application-demo-ui:latest
      container_name: organizer-ui
      restart: always
      ports:
         - "80:80"

   postgres-service:
      image: postgres:15.1-alpine
      container_name: postgress-db
      restart: always
      environment:
         - POSTGRES_DB=organizer_db
         - POSTGRES_PASSWORD=password
         - POSTGRES_USER=hugo
      volumes: 
         - db-data:/var/lib/postgresql/data

   organizer-service:
      image: ghcr.io/felixsteinke/organzier-application-demo-api:latest
      container_name: organizer-api
      restart: always
      depends_on:
         - postgres-service
      environment: 
         - PostgresDB__Host="postgres-service:5432" 
         - PostgresDB__Database=organizer_db
         - PostgresDB__Username=postgres
         - PostgresDB__Username=hugo 
         - PostgresDB__Password=password
      expose:
         - 80
      ports:
         - "8080:80"

volumes: 
   db-data: