version: '3'

services:
   postgres-service:
      image: postgres:15.1-alpine
      container_name: postgress-db
      restart: always
      environment:
         - POSTGRES_DB=organizer_db
         - POSTGRES_PASSWORD=password
      volumes: 
         - postgres:/var/lib/postgres

   organizer-service:
      build: ../organizer-api
      image: ghcr.io/felixsteinke/organzier-application-demo:local
      container_name: organizer-api
      restart: always
      depends_on:
         - postgres-service
      environment: 
         - ConnectionStrings__PostgresDB="Host=postgres-service:5432;Database=organizer_db;Username=postgres;Password=password"
      expose:
         - 80
      ports:
         - "8080:80"

volumes: 
   postgres: