version: '3'

services:

   organizer-postgres-service:
      image: postgres:15.1-alpine
      container_name: organizer-postgres
      restart: always
      environment:
         - POSTGRES_DB=organizer_db
         - POSTGRES_USER=hugo
         - POSTGRES_PASSWORD=password
      volumes:
         - db-data:/var/lib/postgresql/data

   organizer-api-service:
      image: ghcr.io/felixsteinke/organzier-application-demo-api:latest
      container_name: organizer-api-github
      restart: always
      depends_on:
         - organizer-postgres-service
      environment:
         - PostgresDB__Host=organizer-postgres-service:5432
         - PostgresDB__Database=organizer_db
         - PostgresDB__Username=hugo
         - PostgresDB__Password=password
      ports:
         - "8088:80"

   organizer-ui-service:
      image: ghcr.io/felixsteinke/organzier-application-demo-ui:latest
      container_name: organizer-ui-github
      restart: always
      depends_on:
         - organizer-api-service
      environment:
         - BACKEND_API_HOST=http://host.docker.internal:8088
      ports:
         - "80:80"

volumes:
   db-data:
